import type { Metadata } from "next";
import { Inter, Noto_Sans_Thai } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";
import "@smastrom/react-rating/style.css";

import SessionProvider from "../SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Sans_Thai({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${noto.className} flex flex-col min-h-screen`}>
        <SessionProvider session={session}>
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
